## Server
server:
  port: 9001

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/twitter?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: passw

jwt:
  secret: ${JWT_SECRET:PcAGlxBvND20hEw+7U9NA0qLbKUT12+lSkzU/73y+FzInzs+NZEHagSiC+HyoCEejKGcEshVlfUUXoKBrh1QIw==}

ums:
  host: http://localhost
  port: 9000
  paths:
    user: /users/user

