apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: twitter-app
type: Opaque
stringData:
  jwt-secret: "PcAGlxBvND20hEw+7U9NA0qLbKUT12+lSkzU/73y+FzInzs+NZEHagSiC+HyoCEejKGcEshVlfUUXoKBrh1QIw=="
  mysql-root-password: "passw"
  mysql-password: "passw"
