apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-twitter
  namespace: twitter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-twitter
  template:
    metadata:
      labels:
        app: mysql-twitter
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "twitter"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-twitter-pvc
